### PR TITLE
PR: Migrate from heroku to fly.io issue #45

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] #45

See: https://auth-plug.fly.dev/admin

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab should be a quick one to review as mostly deployment (Fly.io) boilerplate code. 🤞 
Thanks. 🙏

**Review by nelsonic — COMMENTED** [review]
LGTM 😜

**Comment by SimonLab** [comment]
Just noticed the merge conflicts:
image

**Comment by nelsonic** [comment]
Merge conflicts resolved. 👌

**Comment by SimonLab** [comment]
I think we can also run `mix deps.clean --unused --unlock` to remove deleted dependencies

https://hexdocs.pm/mix/1.12/Mix.Tasks.Deps.Clean.html

**Comment by nelsonic** [comment]
Good call. Done. ✅

**Review by SimonLab — APPROVED** [review]

**Pull request merged**
